### PR TITLE
cmake: Link MODULE library dependencies privately

### PR DESCRIPTION
**Pull request by bradking**
Avoid exposing private dependencies of loadable modules to consuming applications using CMake.

Cc: @chuckatkins

### CODE REVIEW

**Comment by chuckatkins** [comment]
@eisenhauer this fixes some dependency issues when linking statically.

**Comment by eisenhauer** [comment]
I saw this, but wanted to test it and hadn't had a chance yet.  In particular I was curious why the evpath library was itself in the link set for the transports.  It looks like it was there prior to these mods, but none of the modules should reference anything from the main library (though they do need an include file).  This question isn't related to the PRIVATE tag.  Just about the need for that dependency.

**Comment by chuckatkins** [comment]
The transport plugins use the EVPath API so they need to link to it.  Since they're `MODULE` libraries then nothing links to them so their depencies should never really be exported, conceptually all module lib dependencies

**Comment by eisenhauer** [comment]
I think none of them should actually be referencing symbols defined in the evpath library because that sort of thing breaks on some platforms.  What they need are the config.h from the build directory and some of the types defined in evpath.h and cm_transport.h.  No actual symbols.  (Where evpath functions need to be called from those modules, we pass in function pointers by design.)

**Comment by chuckatkins** [comment]
We could probably use a generator expression to make it a compile-only dependency and not a link dependency, but I'd say it's orthogonal to this change.

@bradking?

**Comment by eisenhauer** [comment]
Agree that it's orthogonal.  Just happened to notice at this time and wonder what was up with it as a link dependency should not be necessary.  Happy to merge this and tackle the other in a different PR if that works.

**Comment by chuckatkins** [comment]
I think what you'd need to do is create an interface library that only has the header dependency and then the modules could use that instead of the EVPath target.

**Comment by eisenhauer** [comment]
It looks like the link dependency was added in the huge reorg of two years ago to help integrate with ADIOS2, and was just not noticed.  How about I merge this, but ask you guys to follow up with the interface library so that you can verify that it doesn't have any deleterious effects on ADIOS.

**Comment by chuckatkins** [comment]
Please close in lieu of #36

**Pull request closed without merging**
