### PR TITLE
Test CI (don't merge this)

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by chuckatkins** [comment]
@bradking looks like the linking issue is resolved

@eisenhauer  looks like you've got linux and mac ci now :-)

**Comment by eisenhauer** [comment]
Thanks much @chuckatkins !  I had thought of this vaguely before, but was daunted by the multi-package dependencies and how much time it would take me to figure all this out from scratch.  Your help is much appreciated!

**Comment by chuckatkins** [comment]
The dependency tree can be a real pita but even though there's a handful of them here they're all pretty small so building all the dependencies takes less than a minute (libfabric, atl, dill, ffs, enet).  The complete cycle time is only 6 and a half minutes: 1m for dependencies, 30s for configure and build, and 5m to test.

**Comment by chuckatkins** [comment]
Closing this since the ci has now been validated to pass.

**Comment by bradking** [comment]
>  looks like the linking issue is resolved

Thanks!

**Pull request closed without merging**
