### PR TITLE
Restore ATL dependency on transport modules

### PR DESCRIPTION
**Pull request by chuckatkins**
It seems the removal of the ATL dependency was a bit overzealous

### CODE REVIEW

**Comment by chuckatkins** [comment]
@eisenhauer @bradking

Tested on mac and linux

**Comment by bradking** [comment]
ADIOS2's CI is still [unhappy](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=ADIOS&showfilters=0&limit=100&value1=1135b2285ea32ae09e000408d3fab5afe58c4992&showfeed=0).  I think this restoration missed `cmenet`.

**Comment by chuckatkins** [comment]
Ugh, I'll fix it.

@eisenhauer would you be opposed to me adding some very basic ci capabilities to EVPath?  Nothing so elaborate as ADIOS but enough to make sure these things are caught.

**Comment by bradking** [comment]
From a quick glance at the net diff before and after #36 and #37 I suspect the modules were getting `atl::atl` transitively through `evpath` before.  Now it needs to be explicit.  At least `cmenet` is still missing it.  I don't know what others need it though.

**Pull request merged**
