### PR TITLE
WIP: Fix memory leaks

### PR DESCRIPTION
**Pull request by KyleFromKitware**

### CODE REVIEW

**Comment by eisenhauer** [comment]
The fix ip_config.c is proper.  The one in cmsockets probably needs more.  In particular, the original commit (July 17 2012, imported from SVN) looks like it created the same leak in cmudp.c.  Also, while the use of get_transport_characteristics() as is doesn't create a leak, it should probably have an add_ref_attr_list() in each of the get_transport_characteristics() and a free_attr_list() in transport_is_reliable() to to free it.  That would be more consistent with other conventions for attribute lists returned by functions... Happy to do that separately if that's easier.

**Comment by KyleFromKitware** [comment]
> Happy to do that separately if that's easier.

Yes, please... I'm not very familiar with the structure of EVPath, and this turned up while I was looking for memory leaks in ADIOS.

**Comment by eisenhauer** [comment]
No worries, I've been tilting at that windmill myself lately.  FYI, there are things in EVPath that are designed to remain persistent as long as the process exists.  They are free'd by atexit() handlers (free_global_transports() and free_foreign_handlers()), but in the past I've seen stability issues in ADIOS when these handlers are enabled.  Since freeing the memory just before exit improves nothing except valgrind and asan results, I've been willing to accept those "leaks", though I imagine trying again would be worthwhile sometime.

**Comment by KyleFromKitware** [comment]
>  FYI, there are things in EVPath that are designed to remain persistent as long as the process exists.

No worries, we can add an exception file to the ASAN build so the builds appear clean.

**Comment by KyleFromKitware** [comment]
Since `cmsockets.c` is being taken care of by #31, I have removed that commit from this PR.

**Pull request merged**
