### PR TITLE
Add optional settings

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by eisenhauer** [comment]
So, I'm having second thoughts about this and the UGNI thing.  Of the top of my head, I was thinking that we were just checking for UGNI to add the appropriate link flags to the libfabric, but in retrospect I think it was a little more complex.  The deal is that the libfabric transport in EVPath has been tried, and works, with at least some version of the IB and UGNI providers in libfabric.  (libfabric is still very far from it's goal of letting you write easily portable RDMA code.) The evpath transport is unlikely to work with other libfabric providers (and pointless to use if only sockets are available).   So the test for "IF INFINIBAND or UGNI" then find_package(libfabric) had us only looking for libfabric if we thought it would work.  (And then trying to add appropriate link flags for it.)  That's probably being overly cautious, particularly since EVPath only actually uses libfabric if you tell it to at runtime.  And the version with "if IB find_package(libfabric)" prevents us from looking for it on Titan.  Probably what we should do is to always look for libfabric and build with it if it's available..

**Comment by chuckatkins** [comment]
The libfabric logic is the same as before any CMake rework I did, i.e always search for it then use it if found.  The `if(ib or gni)` check guards whether or not to try to enable nnti.

**Comment by eisenhauer** [comment]
Whoops.   Yes, NNTI.   Damn, I really need to spend more than the couple minutes I had free looking at this.  Yes, it’s NNTI that’s currently our only working RDMA transport on Titan with UGNI.  That was inside a if(HAVE_IBVERBS OR HAVE_UGNI) before and now it's just if(HAVE_IBVERBS), so we wouldn't built it on Titan.  We should probably just use it if we find it.

**Comment by chuckatkins** [comment]
It's easy enough to make work either way.  Would you rather I restore the ugni check or treat it like libfabric and just use it if we find it?

**Pull request merged**
