### PR TITLE
Add GitHub Actions CI

### PR DESCRIPTION
**Pull request by chuckatkins**

### CODE REVIEW

**Comment by eisenhauer** [comment]
I think all actions enabled, but let me know what I might need to do (or when you're ready to merge).

**Comment by chuckatkins** [comment]
@eisenhauer any idea what's up with the enet / mac test failures: https://github.com/chuckatkins/evpath/runs/505811274 ?

**Comment by eisenhauer** [comment]
Possible firewall issues interfering with local communications.  Assuming that the IP determination went OK (we're using 10.79.0.126), then what it looks like is that we're not able to send a UDP packet to ourself.  Somewhat odd if sockets are working (because it's the same basic mechanism, IP determination, etc. just TCP packets) but of course TCP and UDP are usually treated differently in firewall and NAT rules.  You might try forcing it to use the loopback interface (set environment variable CM_IP to 127.0.0.1.

**Comment by eisenhauer** [comment]
Or, is it sorted?

**Comment by chuckatkins** [comment]
@eisenhauer It should be good to go now: https://github.com/chuckatkins/evpath/runs/506383182

using localhost fixed the mac tests but there's still a few issues.  I ended up just disabling the one problematic test (see in the run.sh the EXCLUDE variable).  It should hit your 90% use case as it in now though and help prevent the previously seen issues from coming up.

**Comment by chuckatkins** [comment]
Once this is merged then you'll start seeing the checks run on new pr's. I'll push a test one just to be sure afterwards.

**Comment by chuckatkins** [comment]
Note that this also fixes the enet atl link issue since it was needed for the ci to pass.

**Comment by eisenhauer** [comment]
Looks reasonable.  The excluded test is trying to send a larger amount of data, and may be sensitive to delays when running on heavily loaded hardware (our local nightly tests didn't generally experience that difficulty).  I can poke at it later to see what might be going on.  In the meantime, will merge.

**Pull request merged**
