### PR TITLE
Remove unnecessary link dependencies from transport modules

### PR DESCRIPTION
**Pull request by chuckatkins**
Replaces #35

### CODE REVIEW

**Comment by chuckatkins** [comment]
@bradking can you double check that this also address the static dependency issue in adios?

**Comment by eisenhauer** [comment]
This looks good to me.  @bradking, let us know if it needs to be tweaked for ADIOS, but otherwise I'm ready to merge.

**Comment by bradking** [comment]
I've confirmed these changes, when applied to EVPath inside ADIOS, fix the problem I was originally trying to fix with #35.

**Comment by chuckatkins** [comment]
@eisenhauer Looks like this is good to go then.  It fixes the export issue @brandking was trying to address in $35, removes the evpath link dependency on the transport modules using an interface library like you wanted in https://github.com/GTkorvo/evpath/pull/35#issuecomment-597847061, and as a bonus, removes yet another link dependency on ATL that wasn't actually used by any of the transport mopdules.

**Comment by bradking** [comment]
@chuckatkins ADIOS2's CI is [unhappy](https://open.cdash.org/index.php?compare1=61&filtercount=1&field1=revision&project=ADIOS&showfilters=0&limit=100&value1=b44a5e43487aa1d1f670cd51b2b379201ca3b042&showfeed=0) with these changes on macOS.  My local testing was only on Linux.

**Comment by bradking** [comment]
For reference, here are some of the errors:

<details>

```
Undefined symbols for architecture x86_64:
  "_add_attr", referenced from:
      _libcmsockets_LTX_initiate_conn in cmsockets.c.o
      _initiate_conn in cmsockets.c.o
      _libcmsockets_LTX_non_blocking_listen in cmsockets.c.o
      _socket_accept_conn in cmsockets.c.o
  "_add_int_attr", referenced from:
      _libcmsockets_LTX_initialize in cmsockets.c.o
  "_add_ref_attr_list", referenced from:
      _libcmsockets_LTX_get_transport_characteristics in cmsockets.c.o
  "_attr_atom_from_string", referenced from:
      _libcmsockets_LTX_initialize in cmsockets.c.o
      _get_IP_config in ip_config.c.o
      _get_qual_hostname in ip_config.c.o
  "_create_attr_list", referenced from:
      _libcmsockets_LTX_initiate_conn in cmsockets.c.o
      _libcmsockets_LTX_non_blocking_listen in cmsockets.c.o
      _socket_accept_conn in cmsockets.c.o
      _libcmsockets_LTX_initialize in cmsockets.c.o
  "_free_attr_list", referenced from:
      _libcmsockets_LTX_initiate_conn in cmsockets.c.o
      _socket_accept_conn in cmsockets.c.o
      _free_socket_data in cmsockets.c.o
  "_get_string_attr", referenced from:
      _get_IP_config in ip_config.c.o
      _get_qual_hostname in ip_config.c.o
  "_query_attr", referenced from:
      _initiate_conn in cmsockets.c.o
      _libcmsockets_LTX_self_check in cmsockets.c.o
      _libcmsockets_LTX_connection_eq in cmsockets.c.o
      _libcmsockets_LTX_non_blocking_listen in cmsockets.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
</details>

`cmsockets.c` may need `atl`.

**Comment by chuckatkins** [comment]
Working on it, will have a fix shortly.

**Comment by eisenhauer** [comment]
If this is popping up for sockets in that environment, then they all likely need that.  They'll all be doing similar attribute manipulations...

**Comment by bradking** [comment]
I see #37, thanks.

**Pull request merged**
